# Generated by Django 6.0.2 on 2026-02-08 09:06

import contact.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(help_text='Primary contact number with country code.', max_length=20, validators=[contact.validators.validate_phone_number], verbose_name='contact number')),
                ('whatsapp_number', models.CharField(blank=True, default='', help_text='WhatsApp number with country code (optional).', max_length=20, validators=[contact.validators.validate_phone_number], verbose_name='WhatsApp number')),
                ('whatsapp_link', models.URLField(blank=True, default='', help_text='WhatsApp click-to-chat URL (e.g., https://wa.me/1234567890)', max_length=500, validators=[contact.validators.validate_safe_url], verbose_name='WhatsApp link')),
                ('instagram_link', models.URLField(blank=True, default='', help_text='Instagram profile URL.', max_length=500, validators=[contact.validators.validate_safe_url], verbose_name='Instagram link')),
                ('youtube_link', models.URLField(blank=True, default='', help_text='YouTube channel URL.', max_length=500, validators=[contact.validators.validate_safe_url], verbose_name='YouTube link')),
                ('x_link', models.URLField(blank=True, default='', help_text='X (formerly Twitter) profile URL.', max_length=500, validators=[contact.validators.validate_safe_url], verbose_name='X (Twitter) link')),
                ('linkedin_link', models.URLField(blank=True, default='', help_text='LinkedIn company or profile URL.', max_length=500, validators=[contact.validators.validate_safe_url], verbose_name='LinkedIn link')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='If unchecked, this contact info will not be displayed.', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'contact info',
                'verbose_name_plural': 'contact info',
                'ordering': ['-created_at'],
            },
        ),
    ]
