# Generated by Django 6.0.2 on 2026-02-08 08:41

import catalog.validators
import homepage.models
import homepage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desktop_image', models.ImageField(blank=True, help_text='Optional desktop image. Allowed: JPG, PNG, WEBP. Max: 5MB.', null=True, upload_to=homepage.models.hero_desktop_image_path, validators=[catalog.validators.validate_image], verbose_name='desktop image (optional)')),
                ('desktop_video', models.FileField(blank=True, help_text='Optional desktop video. Allowed: MP4, WEBM. Max: 50MB.', null=True, upload_to=homepage.models.hero_desktop_video_path, validators=[homepage.validators.validate_video], verbose_name='desktop video (optional)')),
                ('mobile_image', models.ImageField(help_text='Required mobile image. Allowed: JPG, PNG, WEBP. Max: 5MB.', upload_to=homepage.models.hero_mobile_image_path, validators=[catalog.validators.validate_image], verbose_name='mobile image (required)')),
                ('mobile_video', models.FileField(help_text='Required mobile video. Allowed: MP4, WEBM. Max: 50MB.', upload_to=homepage.models.hero_mobile_video_path, validators=[homepage.validators.validate_video], verbose_name='mobile video (required)')),
                ('is_active', models.BooleanField(default=True, help_text='If unchecked, hero section will not be displayed.', verbose_name='is active')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'homepage hero',
                'verbose_name_plural': 'homepage hero',
            },
        ),
    ]
