# Generated by Django 6.0.2 on 2026-02-08 06:56

import catalog.models
import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Unique name for this collection.', max_length=255, unique=True, verbose_name='name')),
                ('image', models.ImageField(help_text='Collection image. Allowed formats: JPG, PNG, WEBP. Max size: 5MB.', upload_to=catalog.models.collection_image_upload_path, validators=[catalog.validators.validate_image], verbose_name='image')),
                ('slug', models.SlugField(editable=False, help_text='Auto-generated URL-safe identifier.', max_length=300, unique=True, verbose_name='slug')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this collection should be displayed to customers.', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the collection was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the collection was last updated.', verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'collection',
                'verbose_name_plural': 'collections',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', '-created_at'], name='catalog_col_is_acti_1b164d_idx')],
            },
        ),
    ]
