# Generated by Django 6.0.2 on 2026-02-08 07:22

import catalog.models
import catalog.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Product name.', max_length=255, verbose_name='name')),
                ('slug', models.SlugField(editable=False, help_text='Auto-generated URL-safe identifier.', max_length=300, unique=True, verbose_name='slug')),
                ('description', models.TextField(help_text='Detailed product description.', verbose_name='description')),
                ('material_info', models.TextField(blank=True, default='', help_text='Material and care instructions.', verbose_name='material info')),
                ('price', models.DecimalField(decimal_places=2, help_text='Current selling price.', max_digits=10, verbose_name='price')),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price for showing discounts. Must be >= price.', max_digits=10, null=True, verbose_name='compare at price')),
                ('main_image', models.ImageField(help_text='Main product image for listings. Allowed: JPG, PNG, WEBP. Max: 5MB.', upload_to=catalog.models.product_image_upload_path, validators=[catalog.validators.validate_image], verbose_name='main image')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this product is visible to customers.', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('collection', models.ForeignKey(help_text='The collection this product belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.collection', verbose_name='collection')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Gallery image. Allowed: JPG, PNG, WEBP. Max: 5MB.', upload_to=catalog.models.product_gallery_upload_path, validators=[catalog.validators.validate_image], verbose_name='image')),
                ('alt_text', models.CharField(blank=True, default='', help_text='Alternative text for accessibility.', max_length=255, verbose_name='alt text')),
                ('position', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first).', verbose_name='position')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='catalog.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product image',
                'verbose_name_plural': 'product images',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('ONE_SIZE', 'One Size')], help_text='Size option.', max_length=20, verbose_name='size')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Available stock for this size.', verbose_name='quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='catalog.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product size',
                'verbose_name_plural': 'product sizes',
                'ordering': ['size'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['collection', 'is_active', '-created_at'], name='catalog_pro_collect_6b28ba_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', '-created_at'], name='catalog_pro_is_acti_ed6a39_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productsize',
            unique_together={('product', 'size')},
        ),
    ]
